name: build

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+'

# NOTE: I'd love to push to github package registry instead of dockerhub, but only dockerhub images can be used in github actions as containers
# weird that github products don't work together and require a third-party ¯\_(ツ)_/¯
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: maximiliancsuk/go-build
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: "./Dockerfile"
          push: true
          build-args: |
            version=${{ env.VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

